export const ERROR_CODES = {
  AUTH_401_UNAUTHORIZED: "AUTH_401_UNAUTHORIZED",
  COMMON_400_VALIDATION: "COMMON_400_VALIDATION",
  COMMON_404_NOT_FOUND: "COMMON_404_NOT_FOUND",
  COMMON_500_INTERNAL: "COMMON_500_INTERNAL"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
